version: '2.3'

networks:
  snare_local:
    name: snare
    ipam:
      driver: default
      config:
        - subnet: "192.168.5.0/24"
          gateway: "192.168.5.1"

services:

# Snare service
  snare:
    build: ./snare
    container_name: snare
    restart: always
    stop_signal: SIGKILL
    tty: true
    networks:
     - snare_local
    dns:
     - 10.12.0.101
     - 8.8.8.8
     - 4.4.4.4
    ports:
     - "80:80"
    image: "mushorg/snare:latest"
